### ISSUE TITLE
Get parts together for kill switch & battery fusing

### ISSUE THREAD

**Issue by davidlenfesty** [UofA-SPEAR/pcb_designs#36]
[Fuseholder](https://www.digikey.ca/product-detail/en/Littelfuse+Inc./01520008Z/F10741-ND/2518487)

[Example Relay](https://www.digikey.ca/product-detail/en/Omron+Electronics+Inc-EMC+Div/G9TB-U1ATH-E+DC12/Z8844-ND/8593135]

I think I want the relays mounted high side and the fuses mounted low side on the batteries.

I would like a common ground during normal operation, but it doesn't make a difference when the fuse blows, so that doesn't matter.

# Tasks:
- [ ] Find all mating parts for fuseholder
- [ ] Find actual relay
- [ ] Find supplier of small amount of large wire.
- [ ] Find killswitch with better terminals.
- [ ] Spec any bolts we need.
- [ ] Design a 3d-printed plate to mount these onto.
